- name: 设置集群模式
  shell: docker exec -it {{ project_name }}-redis-{{ item.index }} sh -c 'echo "yes" | redis-cli -a {{ redis_password }} --cluster create {{ redis_cluster_servers }} --cluster-replicas 1'
  with_random_choice: "{{ hostvars[inventory_hostname].redis }}"
