---

- import_tasks: init.yml
  become: true
  when: hostvars[inventory_hostname].nginx is defined
  tags: init

- import_tasks: run.yml
  when: hostvars[inventory_hostname].nginx is defined
  tags: run

- import_tasks: stop.yml
  when: hostvars[inventory_hostname].nginx is defined
  tags: stop

- import_tasks: reload.yml
  when: hostvars[inventory_hostname].nginx is defined
  tags: reload
